const BACKEND_PYTHON = "./backend/.venv/bin/python";

module.exports = {
  apps: [
    {
      name: "backend",
      cwd: "./backend",
      script: "../backend/.venv/bin/uvicorn",
      interpreter: "none",
      args: "app.main:app --host 0.0.0.0 --port 8000 --reload",
      env: {
        DATABASE_URL: "sqlite:///./app.db",
        UPLOAD_DIR: "./uploads",
        WORKER_POLL_INTERVAL: "5",
        WORKER_TIMEOUT: "300",
        MAX_FILE_SIZE: "52428800",
        DOTS_OCR_URL: "http://localhost:11434/v1/chat/completions",
        DOTS_OCR_MODEL: "minicpm-v",
        DOTS_OCR_PROMPT_MODE: "Extract all text from this document image. Preserve the layout, headings, tables, and structure. Output as structured markdown.",
        OLLAMA_BASE_URL: "http://localhost:11434",
        OLLAMA_EMBED_MODEL: "nomic-embed-text",
        OLLAMA_LLM_MODEL: "llama3.2",
        CHROMA_PERSIST_DIR: "./chroma_db",
        RAG_N_RESULTS: "5",
        RAG_CONTEXT_WINDOW: "10",
        RAG_MAX_DISTANCE: "0.7",
        CORS_ORIGINS: "http://localhost:5173",
      },
    },
    {
      name: "worker",
      cwd: "./backend",
      script: "../backend/.venv/bin/python",
      interpreter: "none",
      args: "worker.py",
      instances: 3,
      env: {
        DATABASE_URL: "sqlite:///./app.db",
        UPLOAD_DIR: "./uploads",
        WORKER_POLL_INTERVAL: "5",
        WORKER_TIMEOUT: "300",
        DOTS_OCR_URL: "http://localhost:11434/v1/chat/completions",
        DOTS_OCR_MODEL: "minicpm-v",
        DOTS_OCR_PROMPT_MODE: "Extract all text from this document image. Preserve the layout, headings, tables, and structure. Output as structured markdown.",
        OLLAMA_BASE_URL: "http://localhost:11434",
        OLLAMA_EMBED_MODEL: "nomic-embed-text",
        CHROMA_PERSIST_DIR: "./chroma_db",
        RAG_MAX_DISTANCE: "0.7",
      },
    },
    {
      name: "frontend",
      cwd: "./frontend",
      script: "/Users/valarpirai.annadurai/.nvm/versions/node/v22.22.0/bin/node",
      args: "./node_modules/vite/bin/vite.js",
    },
  ],
};
