module.exports = {
  apps: [
    {
      name: "backend",
      cwd: "./backend",
      script: "/Users/valarpirai.annadurai/.local/bin/uv",
      args: "run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload",
      env: {
        DATABASE_URL: "sqlite:///./app.db",
        UPLOAD_DIR: "./uploads",
        WORKER_POLL_INTERVAL: "5",
        WORKER_TIMEOUT: "300",
        MAX_FILE_SIZE: "52428800",
        OLLAMA_BASE_URL: "http://localhost:11434",
        OLLAMA_EMBED_MODEL: "nomic-embed-text",
        OLLAMA_LLM_MODEL: "llama3.2",
        CHROMA_PERSIST_DIR: "./chroma_db",
        RAG_N_RESULTS: "5",
        RAG_CONTEXT_WINDOW: "10",
      },
    },
    {
      name: "worker",
      cwd: "./backend",
      script: "/Users/valarpirai.annadurai/.local/bin/uv",
      args: "run python worker.py",
      instances: 3,
      env: {
        DATABASE_URL: "sqlite:///./app.db",
        UPLOAD_DIR: "./uploads",
        WORKER_POLL_INTERVAL: "5",
        WORKER_TIMEOUT: "300",
        OLLAMA_BASE_URL: "http://localhost:11434",
        OLLAMA_EMBED_MODEL: "nomic-embed-text",
        CHROMA_PERSIST_DIR: "./chroma_db",
      },
    },
    {
      name: "frontend",
      cwd: "./frontend",
      script: "/Users/valarpirai.annadurai/.nvm/versions/node/v22.22.0/bin/node",
      args: "./node_modules/vite/bin/vite.js",
    },
  ],
};
